"""
Stage 5: Execution Awareness
Takes a validated config and ACTUALLY generates a runnable Flask + sqlite3 application.
Zero external dependencies beyond Flask itself (stdlib sqlite3) -> $0, no install friction.
"""
import os
import json

APP_TEMPLATE = '''"""
AUTO-GENERATED by the compiler pipeline. Do not hand-edit; regenerate from config.json instead.
Run: pip install flask && python app.py
"""
from flask import Flask, jsonify, request, render_template_string
import sqlite3, os

app = Flask(__name__)
DB_PATH = os.path.join(os.path.dirname(__file__), "app.db")

SCHEMA_SQL = """
{schema_sql}
"""

def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_conn()
    conn.executescript(SCHEMA_SQL)
    conn.commit()
    conn.close()

init_db()

ROLES = {roles}
PERMISSIONS = {permissions}
PAGES = {pages_json}

{routes}

@app.route("/")
def home():
    nav = "".join(f'<li><a href="{{p["route"]}}">{{p["name"]}}</a></li>' for p in PAGES)
    return render_template_string(f"<h1>Generated App</h1><ul>{{nav}}</ul>")

{page_routes}

if __name__ == "__main__":
    app.run(debug=True, port=5000)
'''

ROUTE_TEMPLATE = '''
@app.route("/api/{table}", methods=["GET", "POST"])
def {table}_collection():
    conn = get_conn()
    if request.method == "POST":
        data = request.get_json(force=True) or {{}}
        cols = {col_list}
        values = [data.get(c) for c in cols]
        placeholders = ",".join("?" * len(cols))
        cur = conn.execute(f"INSERT INTO {table} ({{','.join(cols)}}) VALUES ({{placeholders}})", values)
        conn.commit()
        new_id = cur.lastrowid
        row = conn.execute("SELECT * FROM {table} WHERE id = ?", (new_id,)).fetchone()
        conn.close()
        return jsonify(dict(row)), 201
    rows = conn.execute("SELECT * FROM {table}").fetchall()
    conn.close()
    return jsonify([dict(r) for r in rows])

@app.route("/api/{table}/<int:item_id>", methods=["GET", "PUT", "DELETE"])
def {table}_item(item_id):
    conn = get_conn()
    if request.method == "PUT":
        data = request.get_json(force=True) or {{}}
        cols = {col_list}
        sets = ",".join(f"{{c}} = ?" for c in cols if c in data)
        values = [data[c] for c in cols if c in data]
        if sets:
            conn.execute(f"UPDATE {table} SET {{sets}} WHERE id = ?", values + [item_id])
            conn.commit()
    elif request.method == "DELETE":
        conn.execute("DELETE FROM {table} WHERE id = ?", (item_id,))
        conn.commit()
        conn.close()
        return jsonify({{"deleted": item_id}})
    row = conn.execute("SELECT * FROM {table} WHERE id = ?", (item_id,)).fetchone()
    conn.close()
    if row is None:
        return jsonify({{"error": "not found"}}), 404
    return jsonify(dict(row))
'''

SQL_TYPE_MAP = {"string": "TEXT", "number": "REAL", "date": "TEXT", "integer": "INTEGER"}


def _py_literal(obj) -> str:
    """Serialize to a literal usable directly in generated Python source (unlike json.dumps,
    this yields True/False/None instead of true/false/null)."""
    return json.dumps(obj).replace("true", "True").replace("false", "False").replace("null", "None")


def generate_runtime_app(config: dict, output_dir: str) -> dict:
    os.makedirs(output_dir, exist_ok=True)

    schema_statements = []
    routes_code = []

    for table, meta in config["db_schema"]["tables"].items():
        col_defs = []
        col_names = []
        for col in meta["columns"]:
            if col["name"] == "id":
                col_defs.append("id INTEGER PRIMARY KEY AUTOINCREMENT")
                continue
            sql_type = SQL_TYPE_MAP.get(col["type"], "TEXT")
            col_defs.append(f'{col["name"]} {sql_type}')
            col_names.append(col["name"])
        schema_statements.append(f"CREATE TABLE IF NOT EXISTS {table} ({', '.join(col_defs)});")
        routes_code.append(ROUTE_TEMPLATE.format(table=table, col_list=_py_literal(col_names)))

    page_routes = []
    for page in config["ui_schema"]["pages"]:
        page_routes.append(
            f'@app.route("{page["route"]}")\n'
            f'def page_{page["name"].lower()}():\n'
            f'    return jsonify({{"page": "{page["name"]}", "components": {json.dumps(page["components"])}}})\n'
        )

    app_code = APP_TEMPLATE.format(
        schema_sql="\n".join(schema_statements),
        roles=_py_literal(config["auth_schema"]["roles"]),
        permissions=_py_literal(config["auth_schema"]["permissions"]),
        pages_json=_py_literal(config["ui_schema"]["pages"]),
        routes="\n".join(routes_code),
        page_routes="\n".join(page_routes),
    )

    app_path = os.path.join(output_dir, "app.py")
    with open(app_path, "w") as f:
        f.write(app_code)

    config_path = os.path.join(output_dir, "config.json")
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)

    requirements_path = os.path.join(output_dir, "requirements.txt")
    with open(requirements_path, "w") as f:
        f.write("flask\n")

    return {"app_path": app_path, "config_path": config_path, "requirements_path": requirements_path}


def execution_self_check(output_dir: str) -> dict:
    """
    Execution-awareness proof, two levels:
    1. Compile check: app.py is syntactically valid Python.
    2. Boot check: actually import the generated module so Flask registers all
       routes and sqlite3 initializes the schema against a real DB file.
    """
    import py_compile
    import importlib.util
    import sys

    app_path = os.path.join(output_dir, "app.py")
    try:
        py_compile.compile(app_path, doraise=True)
    except py_compile.PyCompileError as e:
        return {"compiles": False, "boots": False, "error": str(e)}

    try:
        spec = importlib.util.spec_from_file_location("generated_app_module", app_path)
        module = importlib.util.module_from_spec(spec)
        sys.modules["generated_app_module"] = module
        spec.loader.exec_module(module)  # this runs init_db() for real
        route_count = len(list(module.app.url_map.iter_rules()))
        del sys.modules["generated_app_module"]
        return {"compiles": True, "boots": True, "registered_routes": route_count, "error": None}
    except Exception as e:
        return {"compiles": True, "boots": False, "error": str(e)}
